version: '2'
services:
  jenkins:
    build: .
    image: isaacal/jenkins:latest
    container_name: jenkins
    user: jenkins
    volumes:
      - jenkins_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"

volumes:
  jenkins_volume:      